// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb_fwAsILrWGgooqREsrQ3HuVLgr8LiEQ',
    appId: '1:254153548440:android:e57564a6fe973dbdd7e6ed',
    messagingSenderId: '254153548440',
    projectId: 'qbeep-assessement',
    databaseURL: 'https://qbeep-assessement-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qbeep-assessement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNicbML1DmS3Nt0S1ImE5lbNBtwSQ62F8',
    appId: '1:254153548440:ios:81c5737ef7d95083d7e6ed',
    messagingSenderId: '254153548440',
    projectId: 'qbeep-assessement',
    databaseURL: 'https://qbeep-assessement-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qbeep-assessement.firebasestorage.app',
    iosBundleId: 'com.example.qbeepAssessment',
  );
}
